#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

LATEST_TAG=$(git describe --tags --abbrev=0)
LATEST_TAG_TIME=$(echo $(git show -q v0.0.3 --pretty=format:%ai) | grep -Eo '\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\s\+\d{4}')

MAJOR_PATTERN='^BREAKING CHANGE:'
MINOR_PATTERN='^feat:'
PATCH_PATTERN='^fix:'
PATTERN='^(fix|feat|BREAKING CHANGE):'

if [[ $COMMIT_MSG =~ $PATTERN ]];then
  # make change log and tag
  git log --pretty=format:"%H - %aI : %s" --after="($LATEST_TAG_TIME)" | while read line
  do
    echo "$line"
  done >> "$date changelog.txt"
  
fi
