#!/bin/sh

MASTER_REF="refs/heads/master"

git log --pretty=format:"%s" | while read line
do
  echo $line
done

if read local_ref local_sha remote_ref remote_sha
then
    echo "$local_ref $local_sha $remote_ref $remote_sha"
    if [ "$remote_ref" == "$MASTER_REF" ]
    then
        echo "[ERROR] DO NOT PUSH DIRECTLY TO MASTER"
        exit 1
    fi
fi