#!/bin/sh

FORBIDDEN_REF="refs/heads/master"

if read local_ref local_sha remote_ref remote_sha
then
    if [ "$remote_ref" == "$FORBIDDEN_REF" ]
    then
        echo "[ERROR] DO NOT PUSH DIRECTLY TO MASTER"
        exit 1
    fi
fi